config/routes.rb
SimpleIp::Application.routes.draw do

  root to: 'static_pages#home'

  get "patents/new"

  resources :users do
  end
  match '/signup',    		to: 'users#new',          	via: :get
  match '/show',	  		to: 'users#show',			via: :get
  match '/userhome',		to: 'users#user_home_page',	via: :get

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',    to: 'sessions#new',   			via: :get
  match '/signout',   to: 'sessions#destroy',     		via: :delete

  match '/about',     to: 'static_pages#about',    	via: :get
  match '/contact',   to: 'static_pages#contact',  	via: :get
  match '/faq',       to: 'static_pages#faq',      	via: :get
  match '/terms',     to: 'static_pages#terms',    	via: :get
  match '/privacy',   to: 'static_pages#privacy',  	via: :get

end

app/models/patent.rb
class Patent < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	before_save { self.email = email.downcase }
	before_create :create_remember_token

	# user name
	validates :name,
		presence: 		true,
		length: 		{ maximum: 50 }

	# user email
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  	validates :email,
  		presence: 		true,
  		format: 		{ with: VALID_EMAIL_REGEX },
  		uniqueness: 	{ case_sensitive: false }

  	# user password
  	has_secure_password
  	validates :password,
  		length:			{ minimum: 6 }

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

  	def User.digest(token)
  		Digest::SHA1.hexdigest(token.to_s)
	end

  	private

    	def create_remember_token
      		self.remember_token = User.digest(User.new_remember_token)
    	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/patents_controller.rb
class PatentsController < ApplicationController

  # create new pat_record
  def new
  	@patent = Pat_record.new
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
    		if user && user.authenticate(params[:session][:password])
      			sign_in user
      			# redirect_back_or user
      			redirect_to root_url
    		else
      			flash.now[:danger] = 'Oops! You entered an invalid email/password combination.  Please try again.'
      			render 'new'
    	end
	end

	def destroy
    	sign_out
    	redirect_to root_url
  	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def faq
  end

  def home
  end

  def privacy
  end

  def terms
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :signed_in_user, only: [:edit, :update, :user_home_page]
before_action :correct_user,   only: [:edit, :update, :user_home_page]

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		sign_in @user
  		flash[:success] = "Welcome to Simple IP!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'  # this renders the edit view
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    # def signed_in_user
      # unless signed_in?
        # store_location
      	# redirect_to signin_url, notice: "Please sign in."
      # end
    # end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "Simple IP"
			if page_title.empty?
				base_title
				else "#{base_title} | #{page_title}"
			end
	end
end

app/helpers/patents_helper.rb
module PatentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
    	remember_token = User.new_remember_token
    	cookies.permanent[:remember_token] = remember_token
    		# the method cookies.permanent[:remember_token] = remember_token
    		# implements a 'permanent' Ruby method that set the cookie duration to 20 years
    		# and is equivalent to --
    		# cookies[:remember_token] = { value:   remember_token,
            #                			 expires: 20.years.from_now.utc }
    	user.update_attribute(:remember_token, User.digest(remember_token))
    	self.current_user = user
	end

	def signed_in?
		!current_user.nil?
  	end

	def current_user=(user)
    	@current_user = user
  	end

  	def current_user
    	remember_token = User.digest(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token)
  	end

  	def current_user?(user)
    	user == current_user
  	end

  	def signed_in_user
      unless signed_in?
        store_location
      	redirect_to signin_url, notice: "Please sign in."
      end
    end

  	def redirect_back_or(default)
    	redirect_to(session[:return_to] || default)
		session.delete(:return_to)
  	end

  	def store_location
    	session[:return_to] = request.url if request.get?
  	end

  	def sign_out
    	current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    	cookies.delete(:remember_token)
    	self.current_user = nil
  	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = {size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 	<meta name="viewport" content="width=device-width, initial-scale=1">

 	<title><%= full_title(yield(:title)) %></title>

 	<!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

 	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= csrf_meta_tags %>

  	<%= render 'shared/shim' %>

</head>

<body>

	<!-- Bootstrap -->
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>

	<%= render 'shared/header' %>

	<div class="container">
    	<% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>

		<%= yield %>
	</div>

	<%= render 'shared/footer' %>

</body>

	<!--
	<%= debug(params) if Rails.env.development? %>
	->

</html>

app/views/patents/new.html.erb
<h1>Patents#new</h1>
<p>Find me in app/views/patents/new.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">

  <nav>
    <ul>
      	<li><%= link_to "Home", root_path %></li>
  		<!--
  		<li><%= link_to "About", about_path %></li>
  		<li><%= link_to "FAQ", faq_path %></li>
  		-->
  		<li><%= link_to "Privacy", privacy_path %></li>
  		<li><%= link_to "Terms", terms_path %></li>
  		<li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
  <small>
    &copy; 2014 Simple IP.  All Rights Reserved.
  </small>
</footer>

app/views/shared/_header.html.erb
<header>
	<nav class="nav navbar-nav navbar-default navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<%= link_to "simple IP (beta)", root_path, id: "logo" %>

			<ul class="nav navbar-nav navbar-right" role="menu">
				<!--
				<li role="presentation"><%= link_to "Home", root_path %></li>
				<li role="presentation"><%= link_to "FAQ", faq_path %></li>
				<li><%= link_to "Users", '#' %></li>
				-->

				<% if signed_in? %>

					<!-- dropdown needs to be fixed
					<div class="nav navbar-nav">

					<li class="dropdown" id="dropdownMenu1" data-toggle="dropdown">
						<a href="#">
						Account <b class="caret"></b>
              			</a>
            		<ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu1">
            		-->
                		<li role="presentation"><%= link_to "My Home Page", root_url %></li>
                		<li role="presentation"><%= link_to "My Profile", current_user %></li>
                		<li role="presentation"><%= link_to "Edit My Profile", edit_user_path(current_user) %></li>
                		<li role="presentation" class="divider"></li>
                		<li role="presentation">
                  			<%= link_to "Sign out", signout_path, method: "delete" %>
                		</li>
              		</ul>
            		</li>
          		<% else %>
            		<li role="presentation"><%= link_to "Sign in", signin_path %></li>
          		<% end %>
        	</ul>
      	</div>
	</nav>
</header>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

app/views/static_pages/_draft_home_text.html.erb
<p class="lead">We provide simple patent organization and visualization tools.</p>

<p class="lead">You get unparalleled insight into your patent clusters.</p>

<p class="lead">And, it's free (well, up to a point).</p>

<p>The process is simple.  Just upload your list of patents or patent publications and use our tools to view a rich set of patent data.</p>

<div class="row">
	<div class="col-md-2">
		<h4>Discover.</h4>
	</div>
	<div class="col-md-8">
		<p>You provide the patents - even your own patent portfolio. We provide tools for insight.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-2">
		<h4>Organize.</h4>
	</div>
	<div class="col-md-8">
		<p>Patents provide a huge amount of information.  You decide what information you want to see, and how you want to see it.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-2">
		<h4>Share.</h4>
	</div>
	<div class="col-md-8">
		<p>Instead of dumping data into spreadsheets or attaching PDFs to emails, use our tools to share your patent information with others in your trusted network.</p>
	</div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About Simple IP</h1>

<!--

<p>Managing patents shouldn't be a chore.</p>

<p>Developed by experienced patent practitioners, Simple IP provides a simple platform that allows you to discover, organize and share patents.</p>

-->

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact Us</h1>

<p>If you have questions, please contact the person who sent you the link to this site.</p>

app/views/static_pages/faq.html.erb
<% provide(:title, 'Frequently Asked Questions') %>

<h1>Frequently Asked Questions</h1>

<!--

<p class="lead">Do you provide a patent search function?</p>
<p>No.  We don't have a better way to search for patents than those offered by the USPTO and other websites.  We suggest that you use those tools if you want to conduct searches.  We've used proprietary patent search engines from a variety of IP analytics firms over the last decade, include semantic or natural language search engines that purport to 'score' results by relevance.  We can't compete with those, nor do we try.  However, we have not found any proprietary search algorithm offered by any IP analytics firm that can find patents with the relevance of references revealed from a search conducted by a skilled patent practitioner using a basic boolean search.</p>

<p>Because of that, we have focused providing tools for organizing and visualizing patent data based on patents that you provide - even if it's organizing your own patent portfolio.</p>

<p class="lead">For which years are patent data available?</p>
<p>We can generally provide more comprehensive data for patents from as early as 1970.  Because patents from before 1970 are made searchable via OCR, data from those patents may not be available or particularly accurate.  The databases that we use are more or less up-to-date, but we can't guarantee that we will have data for patents issued or patent applications published within the last six months or so.</p>

-->

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<% if signed_in? %>

	<%= render 'sessions/user_home_page' %>

<% else %>

<div class="center jumbotron">
	<h1>Welcome to simple IP<small>.beta</small></h1>

	<h3>Discover. Organize. Share.</h3>
	<%= link_to "Join Now!", '#', class: "btn btn-primary btn-lg" %>
	<%= link_to "Sign In", signin_path, class: "btn btn-default btn-lg" %>
</div>

<% end %>

app/views/static_pages/privacy.html.erb
<% provide(:title, 'Privacy') %>

<h1>Our Privacy Policy</h1>

<p>We use reasonable measures to keep your account information and patent data secure.  However, please keep in mind that no website is 100% secure, including this one.</p>

<p>We do track how our website is used, and we may use the information that we obtain from you or through your use of this site to improve this site.</p>

app/views/static_pages/terms.html.erb
<% provide(:title, 'Terms') %>

<h1>Terms of Use</h1>

<p> By using our Simple IP website, you understand and agree to the following:</p>

<ol>
  	<li>We rely on third-party databases, and so cannot guarantee that patent data will be available or accurate for every patent or patent application that you provide.</li>

  	<li>You will not use this site for any malicious purpose.</li>

  	<li>You are responsible for activity occurring under your account name. Please keep your login and password in a safe place.</li>

</ol>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Account') %>

<h1>Update <%= @user.name %>'s Profile</h1>

<div class="container-fluid">
  <div class="row">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		<br>
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
		<br>
		<%= f.label :email %>
		<%= f.text_field :email, class: "form-control" %>
		<br>
		<%= f.label :password %>
		<%= f.password_field :password, class: "form-control" %>
		<br>
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation, class: "form-control" %>
		<br>
		<%= f.submit "Save changes", class: "btn btn-primary" %>
	<% end %>
  </div>
</div>

<!--
<div class="container-fluid">
  <div class="row">
	<div class="gravatar_edit">
      <br><%= gravatar_for @user %></br>
      <a href="http://gravatar.com/emails">Click here to change your user image.</a>
    </div>
  </div>
</div>
-->

app/views/users/new.html.erb
<% provide(:title, 'Join Now!') %>

<h1>Join Now!</h1>

<p>Sorry!  Right now we are in closed beta, and are only allowing use by invitation.</p>

<p>If you would like to be notified when we move to open beta or production mode, please <%= link_to "contact", contact_path %> us.  Thank you for your interest!</p>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<br>
	<%= f.label :name %>
	<%= f.text_field :name, class: "form-control" %>
	<br>
	<%= f.label :email %>
	<%= f.text_field :email, class: "form-control" %>
	<br>
	<%= f.label :password %>
	<%= f.password_field :password, class: "form-control" %>
	<br>
	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation, class: "form-control" %>
	<br>
	<%= f.submit "Create my account", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="container-fluid">
  <div class="row">
    <h1>
    <%= @user.name %>'s Profile
    </h1>
  </div>

  <div class="row">
  	<h3>

	<!--
	<%= gravatar_for @user %>
	-->

	Name: <%= @user.name %>
	<br>Email: <%= @user.email %></br>
	</h3>
</div>

app/views/users/user_home_page.html.erb
<% provide(:title, @user.name) %>

<div class="container-fluid">
  <div class="row">
    <h1>
    <%= @user.name %>'s Home Page
    </h1>
  </div>
</div>